"""add_permission_definitions_and_plan_mappings

Revision ID: 71e2f77f8e8e
Revises: ef4dd376cd25
Create Date: 2026-03-01 09:01:45.511973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e2f77f8e8e'
down_revision: Union[str, None] = 'ef4dd376cd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the hardcoded CHECK constraint that is replaced by dynamic PermissionDefinition
    op.drop_constraint('ck_permissions_permission', 'permissions', type_='check')
    op.create_table('permission_definitions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_definitions_name'), 'permission_definitions', ['name'], unique=True)
    op.create_table('plan_permission_mappings',
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('permission_definition_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_definition_id'], ['permission_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_type', 'permission_definition_id', name='uq_plan_permission_mappings')
    )
    op.create_index(op.f('ix_plan_permission_mappings_permission_definition_id'), 'plan_permission_mappings', ['permission_definition_id'], unique=False)
    op.create_index(op.f('ix_plan_permission_mappings_plan_type'), 'plan_permission_mappings', ['plan_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'ck_permissions_permission',
        'permissions',
        "permission IN ("
        "'transcript:create','transcript:read','transcript:delete',"
        "'analysis:create','analysis:read','analysis:export','analysis:bulk'"
        ")",
    )
    op.drop_index(op.f('ix_plan_permission_mappings_plan_type'), table_name='plan_permission_mappings')
    op.drop_index(op.f('ix_plan_permission_mappings_permission_definition_id'), table_name='plan_permission_mappings')
    op.drop_table('plan_permission_mappings')
    op.drop_index(op.f('ix_permission_definitions_name'), table_name='permission_definitions')
    op.drop_table('permission_definitions')
    # ### end Alembic commands ###
